# Generated by Django 5.1.6 on 2025-03-05 20:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500, verbose_name='Application Link')),
            ],
            options={
                'verbose_name_plural': 'Application Links',
            },
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Opportunity Title')),
                ('category', models.CharField(max_length=50, verbose_name='Opportunity Type')),
                ('date_posted', models.DateField(default=django.utils.timezone.now)),
                ('link', models.URLField(max_length=500, verbose_name='Opportunity Link')),
                ('description', models.TextField(verbose_name='Opportunity Description')),
                ('application_links', models.ManyToManyField(blank=True, related_name='opportunities', to='opportunity.applicationlink')),
            ],
            options={
                'verbose_name_plural': 'Opportunities',
                'ordering': ['-date_posted'],
            },
        ),
    ]
