# Generated by Django 5.1.6 on 2025-03-07 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0003_opportunity_slug_alter_opportunity_og_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='og_image_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
