# Generated by Django 5.1.6 on 2025-03-07 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0005_alter_opportunity_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='slug',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
