# Generated by Django 5.1.6 on 2025-03-07 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0006_alter_opportunity_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='visitorCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
