# Generated by Django 5.1.6 on 2025-03-07 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0007_visitorcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='og_description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
