# Generated by Django 5.1.6 on 2025-03-10 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0009_hackathonopporyunity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HackathonOpporyunity',
            new_name='HackathonOpportunity',
        ),
    ]
