# Generated by Django 5.1.6 on 2025-03-10 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0010_rename_hackathonopporyunity_hackathonopportunity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hackathonopportunity',
            old_name='detail_link',
            new_name='application_link',
        ),
    ]
